# cat ingress-nginx/values-prod.yaml 
controller:
  name: controller
  image:
    repository: anjia0532/google-containers.ingress-nginx.controller
    tag: "v1.1.1"

  dnsPolicy: ClusterFirstWithHostNet
   
  hostNetwork: true

  publishService:  # hostNetwork 模式下设置为false，通过节点IP地址上报ingress status数据
    enabled: false

  kind: DaemonSet

  # nodeSelector: 
  #   role: 

  service:  # HostNetwork 模式不需要创建service
    enabled: false

  tolerations:
    - operator: "Exists"

  resources:
    limits:
      cpu: 100m
      memory: 90Mi
    requests:
      cpu: 100m
      memory: 90Mi

  terminationGracePeriodSeconds: 300

  admissionWebhooks:
    patch:
      enabled: true
      image:
        registry: docker.io
        image: anjia0532/google-containers.ingress-nginx.kube-webhook-certgen
        tag: v1.1.1

defaultBackend:
  enabled: false
  name: defaultbackend
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/varden/defaultbackend-amd64
    tag: "1.5"
