apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-proxy
  labels:
    app: hello-nginx-proxy
    version: v1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-nginx-proxy
      version: v1.0
  template:
    metadata:
      labels:
        app: hello-nginx-proxy
        version: v1.0
    spec:
      containers:
      - name: hello-nginx-proxy
        image: nginx:1.22.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-etc
          readOnly: true
        - mountPath: /usr/share/nginx/html
          name: nginx-html
          readOnly: true

      volumes:
      - name: nginx-etc
        gitRepo:
          repository: https://github.com/deltavoid/nginx_etc.git
          revision: nginx-1.22.0-proxy
          directory: .           
      - name: nginx-html
        gitRepo:
          repository: https://github.com/deltavoid/nginx_html_example.git
          revision: master      
          directory: .     


---

apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-proxy
  labels:
    app: hello-nginx-proxy
spec:
  type: NodePort
  selector:
    app: hello-nginx-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
  
