  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: hello
    # namespace: foo
  spec:
    ingressClassName: nginx
    rules:
      - host: www.example.com
        http:
          paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: hello
                  port:
                    number: 80
              

              