apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-nginx
spec:
  rules:
  - host: www.hello-nginx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-nginx
          servicePort: 80
