apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-network-ingress
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 100.64.0.0/16
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 100.64.0.0/16
